/**
 * app/content/skill-bodies.generated.ts
 *
 * GENERATED FROM app/content/skills/<name>/SKILL.md. DO NOT EDIT BY HAND.
 * Regenerate with: npm run skills:gen
 * Check without writing: npm run skills:gen -- --check
 *
 * WHAT IT IS
 * The nine skill bodies, frontmatter removed, as one typed map. This is the
 * cacheable half of every prompt this app sends.
 *
 * WHY IT EXISTS
 * A founder turn must never fail because a file read failed, so the bodies are
 * compiled in rather than read from disk. And the bytes must be identical for
 * every founder on one route, because that identity is what makes the prompt
 * cache work across roughly 65 people. scripts/gen-skill-prompts.ts is
 * deterministic for that reason, and tests/unit/gen-skill-prompts.test.ts
 * proves it.
 *
 * A key ending in #unforked is the same body with the track marker lines
 * removed and both branches kept. It is what a founder who has not chosen a
 * track yet is handed, so their first Founder Brain can ask either branch.
 *
 * WHAT CALLS IT
 * src/server/routes/agent-content.ts, which adapts it to the SkillBodies port.
 *
 * WHAT IT READS AND WRITES
 * Nothing. It is data.
 */

/** Every body, keyed by the routing table's `skill` field. Sorted, always. */
export const SKILL_BODIES: Readonly<Record<string, string>> = {
  "audience-b2c": [
    "# Audience Engine, B2C",
    "",
    "The B2C equivalent of the outreach engine. Two halves: 25 manual DMs sent live on Saturday, and the inbound machine that keeps working afterwards.",
    "",
    "## The line that does not move",
    "",
    "Say this to the founder early, and use roughly these words rather than writing your own.",
    "",
    "**You send the first message yourself. All 25 of them, from your own app.** Instagram only opens a reply window once the other person has written to you. Anything that gets round that is working against the platform, and accounts doing it get restricted. There is no appeal desk.",
    "",
    "That is not a limit to work around. It is the shape of the whole engine. The 25 go by hand, and the machinery sits on the other side, where somebody has already come to you.",
    "",
    "**What counts as somebody coming to you.** They commented on a post. They replied to a story. They sent you a message. They used a keyword the founder asked for in a caption. That is the list.",
    "",
    "**What does not count.** A follow. A like. A story view. A profile visit. Being on a list the founder built. None of those opens a window, and treating one as though it did is how a founder gets restricted while believing they were on the safe side.",
    "",
    "So build the inbound side properly, and write the 25 as finished messages the founder taps send on. Do not design, recommend, or write copy for anything that reaches a stranger without the founder choosing that person, that message, that moment.",
    "",
    "**If the founder asks to speed the 25 up**, they are asking a fair question and they are not trying to break anything. Do not lecture, and do not quote a rule at them. Say it in three lines, roughly like this:",
    "",
    "> The first message has to come from you. That is Instagram's line, not ours.",
    "> What we build instead is the part that starts the moment somebody comes to you. They comment, they reply, they write in, and the answer is already written and waiting.",
    "> So Saturday is 25 by hand, and the rest of it keeps working after you put your phone down.",
    "",
    "Then go straight to Step 5 and build it with them. A founder who gets a no and nothing else goes and asks somebody else.",
    "",
    "## Prerequisites",
    "",
    "Read `./growth-engine/founder-brain.md`.",
    "",
    "If it genuinely does not exist, stop. Tell the founder to open Founder Brain, or to say \"build my founder brain\", and do not proceed. Do not ask them to describe their business again from scratch, and do not guess at their offer, audience or voice. Everything this skill produces is only as good as the Brain behind it.",
    "",
    "If `track` is not `b2c`, stop and route the founder to the outreach-b2b skill instead.",
    "",
    "Check the Brain for Instagram account type. If it is still personal, tell them to convert to Business or Creator and link a Facebook Page before anything else works.",
    "",
    "## Step 1: targeting",
    "",
    "Engagement-based, not firmographic. Build a list of 25 real accounts from:",
    "",
    "- People who commented on a competitor's recent posts",
    "- Hashtag participants in their niche",
    "- People who already engaged with the founder's own content",
    "- Local accounts, if the business is location-based",
    "- Followers of adjacent, non-competing accounts",
    "",
    "Write the method as a repeatable instruction, not a one-off list. The founder builds the 25 as homework in about an hour.",
    "",
    "## Step 2: 25 DM openers",
    "",
    "One per target account, sent by hand from the founder's own app on Saturday.",
    "",
    "Rules:",
    "- Reference something actually specific to that account. A post, a comment, a bio detail.",
    "- Two sentences maximum. Long DMs do not get read.",
    "- No pitch in the first message. The goal is a reply, not a sale.",
    "- No mass-personalisation tells. If it reads like a template with a name swapped, rewrite it.",
    "- Written in the founder's captured voice.",
    "",
    "Write them in batches of 5, so the founder can check quality as it goes. Ask them to paste in the account handle plus whatever detail they have. Batches are how the 25 get written. They still go out one at a time, on the day, in the founder's own app.",
    "",
    "Output to `./growth-engine/dm-openers.md`, numbered, with the target handle against each.",
    "",
    "**Pacing warning, include it in the output file:** 25 DMs fired in a rapid burst can trigger Instagram action blocks, especially on younger or low-activity accounts. Send them spread across the Saturday afternoon, a few at a time with gaps, from an account that has been used normally in the weeks before. Never race through the list.",
    "",
    "## Step 3: hook bank",
    "",
    "30 hooks for short-form content and DM openers. Categorised: curiosity, contrarian, result, mistake, question, story-open.",
    "",
    "Hooks do more work per word than anything else a B2C founder writes. Spend real effort here.",
    "",
    "The result category is the one that goes wrong. A result hook is built from a result the Brain records, in the founder's own words, or it is not written. If the Brain has no results yet, write more mistake hooks and more story-open hooks instead, and tell the founder that is what you did and why. Never build a hook around a number the founder did not give you, however modest it sounds. The modest ones are the ones that get published.",
    "",
    "Output to `./growth-engine/hook-bank.md`, grouped by category.",
    "",
    "## Step 4: offer tests",
    "",
    "Three variants of how the offer is framed, to test against each other. Different angle, not different wording. Note what each is testing.",
    "",
    "Add them to `./growth-engine/hook-bank.md` under an Offer tests heading, so the hook bank and the offer tests travel as one file.",
    "",
    "## Step 5: the inbound machine",
    "",
    "This is where the automation lives, and it is fully sanctioned.",
    "",
    "Every flow here starts with something the other person did. If you cannot name that thing in one short phrase, the flow is not inbound and does not get written.",
    "",
    "**Comment-to-DM.** The founder posts, the caption invites a comment keyword, Instagram fires an automatic DM because the user initiated. Write the trigger keyword, the auto-DM message, and the follow-up.",
    "",
    "**DM qualify and book.** A short conversation flow that qualifies the inbound and routes to a booking link or product page. Three or four steps, no interrogation.",
    "",
    "**Link in bio.** A GHL form or calendar destination.",
    "",
    "**Cap the follow-up.** One follow-up, then stop. If they do not reply to the first message and do not reply to the follow-up, the conversation is over and nothing more goes out. Write the stop into the copy, because a flow with no exit carries on at somebody who has already decided.",
    "",
    "Write the copy for each. The workflow itself is a GHL snapshot loaded at the clinic, so do not attempt to build automation here. Copy only.",
    "",
    "**Name the trigger in every label, not just the first one.**",
    "",
    "Write \"Reply, sent when they comment:\" above each piece of copy, every time. Do not use a bare label that says only that a machine sends it.",
    "",
    "Two reasons, and the first is the one that matters to the founder. Every message in this file only goes out because somebody did something first, and a label that says so is the difference between a flow they can check and a flow they have to take on trust. A reader scanning the file should be able to see, at each step, what opened the window.",
    "",
    "The second is practical. A label that does not name the trigger is read as the thing rule 2 refuses, and the refusal costs the whole run, including the two files that had nothing to do with it. Naming the trigger is not a workaround. It is the sentence being accurate about what it describes.",
    "",
    "Output to `./growth-engine/inbound-scripts.md`.",
    "",
    "## Gate",
    "",
    "Audience defined, 25 target accounts identified, 25 DM openers written, hook bank complete, inbound scripts written, Instagram converted to Business or Creator.",
    "",
  ].join('\n'),
  "content-engine": [
    "# Content Engine",
    "",
    "Produces the 30 pieces of content each founder publishes before Atlanta.",
    "",
    "## Prerequisites",
    "",
    "Read `./growth-engine/founder-brain.md`.",
    "",
    "If it genuinely does not exist, stop and tell the founder to open Founder Brain, or to say \"build my founder brain\". Do not guess at their business or voice.",
    "",
    "Read the `track` field. Everything below branches on it.",
    "",
    "## Step 1: pillars",
    "",
    "Propose four content pillars from the Brain. Pillars are the recurring themes the founder can write about indefinitely without repeating themselves.",
    "",
    "Derive them from proof, offer, audience pain, and point of view. Do not use generic marketing pillars.",
    "",
    "**B2B pillars** typically land on: the problem the market misdiagnoses, proof and results, how the work actually gets done, and a contrarian position on the industry.",
    "",
    "**B2C pillars** typically land on: transformation and outcome, behind the scenes, education against a common mistake, and social proof.",
    "",
    "**If the Brain says proof is thin, the proof pillar becomes something else.** Not a thinner version of itself, because a thin proof pillar is where numbers get made up to fill it. On B2B it becomes how the work actually gets done, in the detail nobody outside the trade would know. On B2C it becomes the founder's own story and what they watch go wrong. Both are true, both are theirs, and neither needs a number.",
    "",
    "Show the four with a one-line rationale each. Let the founder cut or swap. Four is the number. Fewer gets repetitive, more gets thin.",
    "",
    "## Step 2: generate",
    "",
    "30 pieces, distributed across the four pillars, weighted toward whichever pillar has the most proof behind it.",
    "",
    "<!-- TRACK:b2b -->",
    "### If track is b2b",
    "",
    "Format mix:",
    "- 20 short posts, 80 to 150 words, for LinkedIn and X",
    "- 6 longer posts, 200 to 300 words, for LinkedIn",
    "- 4 with a soft call to action",
    "",
    "Each post: a specific opening line that earns the second line, one idea, concrete detail from their proof, no generic advice. If the Brain flagged thin proof, lean on point of view and observation rather than inventing results. **Never invent numbers, customers, or outcomes.**",
    "<!-- /TRACK -->",
    "",
    "<!-- TRACK:b2c -->",
    "### If track is b2c",
    "",
    "Format mix:",
    "- 15 short-form video scripts, 20 to 40 seconds, with a hook in the first three seconds",
    "- 8 carousel or multi-frame outlines, frame by frame",
    "- 7 single-image captions",
    "",
    "Scripts need a spoken hook, not a written one. Read them aloud in your head. If the first line does not stop a scroll, rewrite it.",
    "",
    "Include the on-screen text separately from the spoken line where they differ.",
    "<!-- /TRACK -->",
    "",
    "### Both tracks",
    "",
    "Write in the voice captured in the Brain, including the verbatim phrases. Vary opening structure across the 30. Nothing should read as templated.",
    "",
    "**Numbers.** Every number that says something happened has to be one the founder gave you. Counts of dogs, weddings, kitchens, boilers, meals, sessions, callouts, customers or jobs. Money. Percentages. A before and an after. If it is in the Brain, use it and use it exactly as they said it. If it is not in the Brain, do not reach for one.",
    "",
    "There is always something to write instead, and it is usually the better post:",
    "",
    "- **What they have seen.** The fault that turns up job after job. The question every customer asks before anything else.",
    "- **What they do differently.** The step they take that the cheap option skips. That is method, and method needs no number.",
    "- **What they think.** A position they will defend out loud.",
    "- **What one real customer said**, if the Brain records it, in that customer's own words.",
    "",
    "\"We have groomed over 500 dogs\" is a number nobody gave you. \"Most of the dogs I see for the first time have not been brushed out properly in months, and the owner has no idea\" is true, it is theirs, and it is the stronger post.",
    "",
    "If a piece genuinely needs a number, stop and ask the founder for it in one question. Asking is quick. A number they have to correct after it is published is not.",
    "",
    "Generate in batches of 10 and check in between batches. Thirty in one dump is unreviewable and the founder will approve it without reading.",
    "",
    "## Step 3: keeping it running",
    "",
    "Thirty pieces at five a week is six weeks of content. The promise is a content engine, not a one off batch, so the founder needs to know how it refills before they leave Atlanta.",
    "",
    "Set this up now, not later.",
    "",
    "**The refill routine.** Once a month, the founder runs this skill again in refill mode: 30 new pieces, same pillars, same voice, generated against what has happened since. It takes about twenty minutes. Tell them that plainly, because most people assume regenerating means starting over.",
    "",
    "**What feeds it.** Pull the Source material list from the Brain, and add three to five RSS feeds relevant to their audience. Record them in `./growth-engine/rss-feeds.md`. This is a source list, not an automation. When they refill, this is what stops the new batch repeating the last one.",
    "",
    "**What changes between batches.** Ask them to note new proof as it happens: a result, a customer story, a question they got asked twice. Add a running list at the bottom of `content-30.md`. Fresh proof is the difference between month two sounding like month one and month two sounding better.",
    "",
    "**Refill mode.** If the founder is running this skill again and `content-30.md` already exists, read it first. Do not repeat angles that have already been published. Archive the old file as `content-30-[month].md` and write a fresh one.",
    "",
    "## Step 4: export",
    "",
    "Write two files.",
    "",
    "`./growth-engine/content-30.md` for the founder to read and edit. Numbered, grouped by pillar, with the format labelled.",
    "",
    "`./growth-engine/content-30.csv`, the same 30 as a table. Columns: `content`, `platform`, `scheduled_date`, `media_note`.",
    "",
    "Leave `scheduled_date` blank. When a piece goes out is decided later, and not here.",
    "",
    "`media_note` says which of their own clips or photos to use, by name, when they have one that fits. When they do not, it says what to make, plainly, for example \"record talking head, 30 seconds\" or \"screenshot of dashboard\".",
    "",
    "## How these get published",
    "",
    "**Posting is GoHighLevel's job and the founder does it from Claude, not from here.** Once they have connected the GoHighLevel connector to their Claude account, they can ask for these to be posted, a few at a time, and read them first. Say that when you hand the files over, in one line, and do not walk them through it: `docs/WORKING-IN-CLAUDE.md` is where that lives.",
    "",
    "The CSV is the second way in and it stays. A founder who has not connected anything yet, or who would rather do it by hand, has a table they can import or work down. It is also the copy they keep if they ever leave.",
    "",
    "Do not tell a founder the exact import columns GoHighLevel expects. That format changes, nobody here has checked it lately, and a confident wrong answer costs them an afternoon.",
    "",
    "## Step 4b: what they can actually post",
    "",
    "**Ask before you write, and ask once.** A founder gets 30 pieces they cannot publish if you plan a shot list they never agreed to.",
    "",
    "Say it plainly: what clips and photos have you got, and where are they? Pre-work asks them to put everything in their GoHighLevel Media Library, so that is the first place to ask about. If they have things elsewhere, or nothing, take that answer and carry on.",
    "",
    "### What to do with the answer",
    "",
    "**Write all 30 either way. Never write fewer.** A short file hides the problem: it looks finished, and they find out in September that half their month is missing. Thirty pieces with a count on the top is a plan they can act on. Twenty two is a plan that lies.",
    "",
    "**Put the count at the top of the file**, before anything else, in their words:",
    "",
    "> 18 of these need a clip or a photo you have not got yet. Each one says which. They are ready to post the moment you have the picture.",
    "",
    "**Mark every piece that needs something they do not have.** One line, at the end of that piece, saying what it needs. Not a warning, not an apology. A founder scanning the file has to be able to see in one pass which ones are ready today.",
    "",
    "**A piece that needs nothing gets no line.** Marking everything marks nothing.",
    "",
    "### Do not",
    "",
    "Do not refuse to write a piece because the picture is missing. Do not quietly turn a video into a text post to avoid the flag, because that changes what they asked for to make your output look tidier. Do not suggest stock images: a stock photo in a founder's feed reads as a stock photo.",
    "",
    "### If they have nothing at all",
    "",
    "Say so in one sentence at the top, without a lecture. They know. Point them at the pre-work list for their track, say the words are done and waiting, and carry on.",
    "",
    "## Step 5: the check",
    "",
    "Tell the founder their homework is to read all 30 and edit anything that does not sound like them. Not to approve them unread.",
    "",
    "The gate is 30 submitted, not 30 generated. Say that plainly.",
    "",
    "Reading a piece is not approving it. A piece counts towards the gate once it is marked approved, so tell the founder to mark each one as they finish reading it.",
    "",
  ].join('\n'),
  "content-engine#unforked": [
    "# Content Engine",
    "",
    "Produces the 30 pieces of content each founder publishes before Atlanta.",
    "",
    "## Prerequisites",
    "",
    "Read `./growth-engine/founder-brain.md`.",
    "",
    "If it genuinely does not exist, stop and tell the founder to open Founder Brain, or to say \"build my founder brain\". Do not guess at their business or voice.",
    "",
    "Read the `track` field. Everything below branches on it.",
    "",
    "## Step 1: pillars",
    "",
    "Propose four content pillars from the Brain. Pillars are the recurring themes the founder can write about indefinitely without repeating themselves.",
    "",
    "Derive them from proof, offer, audience pain, and point of view. Do not use generic marketing pillars.",
    "",
    "**B2B pillars** typically land on: the problem the market misdiagnoses, proof and results, how the work actually gets done, and a contrarian position on the industry.",
    "",
    "**B2C pillars** typically land on: transformation and outcome, behind the scenes, education against a common mistake, and social proof.",
    "",
    "**If the Brain says proof is thin, the proof pillar becomes something else.** Not a thinner version of itself, because a thin proof pillar is where numbers get made up to fill it. On B2B it becomes how the work actually gets done, in the detail nobody outside the trade would know. On B2C it becomes the founder's own story and what they watch go wrong. Both are true, both are theirs, and neither needs a number.",
    "",
    "Show the four with a one-line rationale each. Let the founder cut or swap. Four is the number. Fewer gets repetitive, more gets thin.",
    "",
    "## Step 2: generate",
    "",
    "30 pieces, distributed across the four pillars, weighted toward whichever pillar has the most proof behind it.",
    "",
    "### If track is b2b",
    "",
    "Format mix:",
    "- 20 short posts, 80 to 150 words, for LinkedIn and X",
    "- 6 longer posts, 200 to 300 words, for LinkedIn",
    "- 4 with a soft call to action",
    "",
    "Each post: a specific opening line that earns the second line, one idea, concrete detail from their proof, no generic advice. If the Brain flagged thin proof, lean on point of view and observation rather than inventing results. **Never invent numbers, customers, or outcomes.**",
    "",
    "### If track is b2c",
    "",
    "Format mix:",
    "- 15 short-form video scripts, 20 to 40 seconds, with a hook in the first three seconds",
    "- 8 carousel or multi-frame outlines, frame by frame",
    "- 7 single-image captions",
    "",
    "Scripts need a spoken hook, not a written one. Read them aloud in your head. If the first line does not stop a scroll, rewrite it.",
    "",
    "Include the on-screen text separately from the spoken line where they differ.",
    "",
    "### Both tracks",
    "",
    "Write in the voice captured in the Brain, including the verbatim phrases. Vary opening structure across the 30. Nothing should read as templated.",
    "",
    "**Numbers.** Every number that says something happened has to be one the founder gave you. Counts of dogs, weddings, kitchens, boilers, meals, sessions, callouts, customers or jobs. Money. Percentages. A before and an after. If it is in the Brain, use it and use it exactly as they said it. If it is not in the Brain, do not reach for one.",
    "",
    "There is always something to write instead, and it is usually the better post:",
    "",
    "- **What they have seen.** The fault that turns up job after job. The question every customer asks before anything else.",
    "- **What they do differently.** The step they take that the cheap option skips. That is method, and method needs no number.",
    "- **What they think.** A position they will defend out loud.",
    "- **What one real customer said**, if the Brain records it, in that customer's own words.",
    "",
    "\"We have groomed over 500 dogs\" is a number nobody gave you. \"Most of the dogs I see for the first time have not been brushed out properly in months, and the owner has no idea\" is true, it is theirs, and it is the stronger post.",
    "",
    "If a piece genuinely needs a number, stop and ask the founder for it in one question. Asking is quick. A number they have to correct after it is published is not.",
    "",
    "Generate in batches of 10 and check in between batches. Thirty in one dump is unreviewable and the founder will approve it without reading.",
    "",
    "## Step 3: keeping it running",
    "",
    "Thirty pieces at five a week is six weeks of content. The promise is a content engine, not a one off batch, so the founder needs to know how it refills before they leave Atlanta.",
    "",
    "Set this up now, not later.",
    "",
    "**The refill routine.** Once a month, the founder runs this skill again in refill mode: 30 new pieces, same pillars, same voice, generated against what has happened since. It takes about twenty minutes. Tell them that plainly, because most people assume regenerating means starting over.",
    "",
    "**What feeds it.** Pull the Source material list from the Brain, and add three to five RSS feeds relevant to their audience. Record them in `./growth-engine/rss-feeds.md`. This is a source list, not an automation. When they refill, this is what stops the new batch repeating the last one.",
    "",
    "**What changes between batches.** Ask them to note new proof as it happens: a result, a customer story, a question they got asked twice. Add a running list at the bottom of `content-30.md`. Fresh proof is the difference between month two sounding like month one and month two sounding better.",
    "",
    "**Refill mode.** If the founder is running this skill again and `content-30.md` already exists, read it first. Do not repeat angles that have already been published. Archive the old file as `content-30-[month].md` and write a fresh one.",
    "",
    "## Step 4: export",
    "",
    "Write two files.",
    "",
    "`./growth-engine/content-30.md` for the founder to read and edit. Numbered, grouped by pillar, with the format labelled.",
    "",
    "`./growth-engine/content-30.csv`, the same 30 as a table. Columns: `content`, `platform`, `scheduled_date`, `media_note`.",
    "",
    "Leave `scheduled_date` blank. When a piece goes out is decided later, and not here.",
    "",
    "`media_note` says which of their own clips or photos to use, by name, when they have one that fits. When they do not, it says what to make, plainly, for example \"record talking head, 30 seconds\" or \"screenshot of dashboard\".",
    "",
    "## How these get published",
    "",
    "**Posting is GoHighLevel's job and the founder does it from Claude, not from here.** Once they have connected the GoHighLevel connector to their Claude account, they can ask for these to be posted, a few at a time, and read them first. Say that when you hand the files over, in one line, and do not walk them through it: `docs/WORKING-IN-CLAUDE.md` is where that lives.",
    "",
    "The CSV is the second way in and it stays. A founder who has not connected anything yet, or who would rather do it by hand, has a table they can import or work down. It is also the copy they keep if they ever leave.",
    "",
    "Do not tell a founder the exact import columns GoHighLevel expects. That format changes, nobody here has checked it lately, and a confident wrong answer costs them an afternoon.",
    "",
    "## Step 4b: what they can actually post",
    "",
    "**Ask before you write, and ask once.** A founder gets 30 pieces they cannot publish if you plan a shot list they never agreed to.",
    "",
    "Say it plainly: what clips and photos have you got, and where are they? Pre-work asks them to put everything in their GoHighLevel Media Library, so that is the first place to ask about. If they have things elsewhere, or nothing, take that answer and carry on.",
    "",
    "### What to do with the answer",
    "",
    "**Write all 30 either way. Never write fewer.** A short file hides the problem: it looks finished, and they find out in September that half their month is missing. Thirty pieces with a count on the top is a plan they can act on. Twenty two is a plan that lies.",
    "",
    "**Put the count at the top of the file**, before anything else, in their words:",
    "",
    "> 18 of these need a clip or a photo you have not got yet. Each one says which. They are ready to post the moment you have the picture.",
    "",
    "**Mark every piece that needs something they do not have.** One line, at the end of that piece, saying what it needs. Not a warning, not an apology. A founder scanning the file has to be able to see in one pass which ones are ready today.",
    "",
    "**A piece that needs nothing gets no line.** Marking everything marks nothing.",
    "",
    "### Do not",
    "",
    "Do not refuse to write a piece because the picture is missing. Do not quietly turn a video into a text post to avoid the flag, because that changes what they asked for to make your output look tidier. Do not suggest stock images: a stock photo in a founder's feed reads as a stock photo.",
    "",
    "### If they have nothing at all",
    "",
    "Say so in one sentence at the top, without a lecture. They know. Point them at the pre-work list for their track, say the words are done and waiting, and carry on.",
    "",
    "## Step 5: the check",
    "",
    "Tell the founder their homework is to read all 30 and edit anything that does not sound like them. Not to approve them unread.",
    "",
    "The gate is 30 submitted, not 30 generated. Say that plainly.",
    "",
    "Reading a piece is not approving it. A piece counts towards the gate once it is marked approved, so tell the founder to mark each one as they finish reading it.",
    "",
  ].join('\n'),
  "founder-brain": [
    "# Founder Brain",
    "",
    "The Founder Brain is the input to every other engine. Nothing else runs without it.",
    "",
    "Output is a single file at `./growth-engine/founder-brain.md` in the founder's working folder.",
    "",
    "**Where the work lives.** Every file this makes for the founder sits in their `growth-engine/` folder, held for them, and they can see and download any of it from Files at any time. There is no folder to remember and nothing to keep in one place. Say this once, near the end, because founders arrive expecting to have to manage it.",
    "",
    "## Before starting",
    "",
    "Check whether `./growth-engine/founder-brain.md` already exists.",
    "",
    "- If it exists and the founder asked to build a new one, show them the current summary and ask whether to update it or start again.",
    "- If it exists and they asked to update, go straight to the section they want to change.",
    "- If it does not exist, run the full intake below.",
    "",
    "Create the `./growth-engine/` folder if it is not there.",
    "",
    "### If they ask to change the track",
    "",
    "\"change my track\" is a trigger on this skill, so a founder asking has reached the right place. It is allowed. Do not tell them it cannot be done, and do not send them to a mentor. There is no escalation path and inventing one leaves them stuck.",
    "",
    "It is the one change that costs a founder work, so it takes one honest exchange first. That is not the same as refusing.",
    "",
    "**Say what it costs, using their own file names.** Everything built off the track was written for the other side. Their Brain stays, their voice profile stays, and the rest is rebuilt.",
    "",
    "**Ask what changed.** Not to talk them out of it. \"I picked wrong in session 1\" is answered differently from \"I want to serve schools as well as parents\". The second one usually wants `hybrid: true` and the same track, and that distinction is worth thirty seconds of asking.",
    "",
    "**If they confirm, do it.** Rewrite the Track line in the file that is already there. Then reopen only the parts that fork on it, which are the audience capture and the channel question. Both are asked differently on each side, and the intake below already knows which. Everything else in the file is still true, so do not re-ask it and do not re-run the full intake.",
    "",
    "**Then say what to expect.** Their old track's files stay where they are and stop appearing in their list, because the list only shows the track they are on. The new track's gates start empty. Name which files they now need and which session covers each.",
    "",
    "If they are hesitating, leave it where it is. They can come back to it, and a track changed twice costs more than a track changed once.",
    "",
    "## Intake",
    "",
    "Ask these in small groups, not all at once. Three or four questions per turn. Reflect back what you heard before moving on. This should feel like a conversation with a sharp consultant, not a form.",
    "",
    "**Say where they are, every single turn.** Open each group by naming the stage",
    "and the count, like `Part 2 of 6: the track fork`. The six are the business, the",
    "track fork, the audience, the offer and proof, the channels, then the voice.",
    "When you finish the last one, say you are writing the file.",
    "",
    "This is not decoration. A founder who cannot see the end of a conversation does",
    "not know whether to give you a quick answer or a careful one, and the ones who",
    "guess wrong give you thin answers early and then run out of patience at the",
    "voice, which is the part everything else is built on. Knowing they are two",
    "thirds of the way through costs you one line and changes what they give you.",
    "",
    "### Group 1: the business",
    "",
    "1. What is the business called, and what does it sell?",
    "2. Who pays you? Be specific about the actual buyer.",
    "3. What stage are you at? Pre-revenue, first customers, under 10k a month, 10 to 50k, above 50k.",
    "4. What do you charge, and how? One-off, subscription, retainer, per unit.",
    "",
    "### Group 2: the track fork",
    "",
    "This is the most important question in the intake. Everything downstream branches from it.",
    "",
    "Ask: **does your revenue come mostly from selling to other businesses, or to individual consumers?**",
    "",
    "- Mostly businesses, so B2B",
    "- Mostly consumers, so B2C",
    "- Genuinely both",
    "",
    "If they say both, do not create a third track. Ask which motion produces more revenue today, or which one they most want to grow over the next 90 days. Record that as `track`, and record `hybrid: true` alongside it. The hybrid flag adjusts tone and examples later. It does not create a separate path.",
    "",
    "Explain briefly why you are asking: the outreach engine works completely differently on each track, and getting this wrong means building the wrong machine.",
    "",
    "<!-- TRACK:b2c -->",
    "**If track is B2C**, ask one more question: do they sell a service people book, or products people buy from a shop? Record the answer as `Model`, either `service` or `ecommerce`. It decides which operations snapshot they get and how their content is shaped. Never ask this of a B2B founder.",
    "<!-- /TRACK -->",
    "",
    "### Group 3: audience",
    "",
    "<!-- TRACK:b2b -->",
    "**If track is B2B**, capture the ICP:",
    "- What kind of company? Industry, size, revenue band, geography.",
    "- Who is the individual you actually sell to? Job title, seniority, department.",
    "- What triggers them to start looking for something like yours?",
    "- Which companies are your best-fit customers today? Name three.",
    "<!-- /TRACK -->",
    "",
    "<!-- TRACK:b2c -->",
    "**If track is B2C**, capture the persona:",
    "- Who is this person? Age range, life stage, situation.",
    "- What do they want that they cannot get right now?",
    "- Where do they already spend attention online? Be specific about platforms and accounts.",
    "- What do they already buy that sits next to your product?",
    "<!-- /TRACK -->",
    "",
    "Do not ask B2B questions of a B2C founder or the reverse. It wastes their time and signals the tool does not understand them.",
    "",
    "### Group 4: offer and proof",
    "",
    "1. What problem do you solve, in one sentence, in their words rather than yours?",
    "2. Why you rather than the obvious alternative?",
    "3. What proof do you have? Results, numbers, named customers, case studies, testimonials, credentials.",
    "4. What do you want more of in the next 90 days? Leads, sales, followers, retention.",
    "",
    "**Ask question 3 in their world, not in business language.** Most founders here run small local businesses, so the countable things are dogs, weddings, kitchens, boilers, meals, sessions, callouts and repeat bookings, not customers and firms. Ask how many they have done, how long they have been doing it, how many come back, and which one went best. Write the numbers down exactly as they said them, and write unknown where they do not know.",
    "",
    "That last part is the important one. A number recorded here is a number every other engine is allowed to use. A gap recorded here is a gap nothing downstream will quietly fill in for them.",
    "",
    "Proof matters more than founders expect. It is the raw material for every post and every message. If they have none, say so plainly and note it, because the content engine will lean on story and point of view instead.",
    "",
    "### The thesis",
    "",
    "From their Group 4 answers, compose one sentence: who they serve, the problem in the customer's own words, and why them rather than the obvious alternative. Read it back and adjust until they would say it out loud to a stranger. This is the thesis. It goes in the Brain, it is pressure-tested in Session 1, and it is part of their Gate 1 submission.",
    "",
    "### Group 5: channels",
    "",
    "- Where do you currently publish, if anywhere?",
    "- Which channels do you have accounts on but do not use?",
    "- **If track is B2C**: is your Instagram a personal account, or Business or Creator? If personal, tell them to convert it now, because publishing and inbound capture will not work without it, and it takes two minutes.",
    "- **If track is B2B**: which provider is their work email on, Google (Gmail or Google Workspace), Microsoft 365, or something else? This decides how they send their 25 messages later, so record it plainly. It is not a technical question to them: \"what do you open your work email in\" gets the answer.",
    "- **If track is B2B**: do you have a business domain with real email sending history, or will you need a fresh domain? A fresh domain needs SPF, DKIM and DMARC configured now, plus ten to twenty real messages a day between now and the event. At 25 messages, correct setup matters more than months of warmup, but it cannot be crammed into the last week, so flag it as a start-today item.",
    "",
    "## Voice capture",
    "",
    "Three paths. Pick based on what they have. Nobody gets stuck here.",
    "",
    "**Important distinction before you start.** The voice must be theirs. Curated content from other people is useful for working out what to write *about*, never for how it sounds. If you train the voice on a competitor, the founder ends up publishing something that reads like an imitation, and their audience can tell. Topics can be borrowed. Voice cannot.",
    "",
    "### Path A: they have writing",
    "",
    "Ask for 10 to 20 samples of anything they have written in their own voice. Posts, emails, newsletters, even long messages. Pasted in, or a file path.",
    "",
    "Read them and extract:",
    "- Sentence length and rhythm",
    "- Vocabulary level and any recurring words or phrases",
    "- How they open and how they close",
    "- Whether they use humour, and what kind",
    "- First person singular or plural",
    "- How direct they are, and how much they hedge",
    "- Formatting habits: lists, line breaks, questions, emoji",
    "",
    "### Path B: they have some writing, but not much",
    "",
    "Five or six real samples is enough to work from. Read them the same way as Path A, then fill the gaps with two or three interview questions from Path C. Say plainly that a smaller sample is fine and that you will check the result with them before anything gets built on it.",
    "",
    "### Path C: they have nothing written",
    "",
    "Many early-stage and B2C founders have no body of writing. This is normal. Do not make it awkward.",
    "",
    "Run a short interview instead, and capture how they *speak*:",
    "- Tell me about the last customer you really enjoyed working with.",
    "- What do people get wrong about your industry?",
    "- What would you say to someone about to make the mistake your product prevents?",
    "- What is the thing you find yourself explaining over and over?",
    "",
    "Their answers to these are the voice sample. Pay attention to how they actually phrase things, not what they say.",
    "",
    "### Source material, all three paths",
    "",
    "Separately from voice, ask what they already read and who they follow in their space. Competitors, industry accounts, newsletters, creators. This is not for voice. It is so the content engine knows what conversations their audience is already having, and what the founder wants to agree with or argue against.",
    "",
    "Record five to ten of these in the Brain under Source material. A founder with a strong point of view and no writing history will produce better content from this than a founder with fifty posts and nothing to react to.",
    "",
    "### Voice profile",
    "",
    "Either path produces the same output: a description specific enough that another writer could imitate it. Include three or four verbatim phrases they actually use.",
    "",
    "Then show the founder a two-sentence sample written in their captured voice and ask: does this sound like you? Adjust until they say yes. Do not skip this check.",
    "",
    "## Writing the file",
    "",
    "Write `./growth-engine/founder-brain.md` in this shape:",
    "",
    "```markdown",
    "# Founder Brain",
    "",
    "- **Founder:**",
    "- **Business:**",
    "- **Track:** b2b | b2c",
    "- **Model:** service | ecommerce, B2C only, leave out for B2B",
    "- **Hybrid:** true | false",
    "- **Stage:**",
    "- **Locked:** YYYY-MM-DD",
    "",
    "## Thesis",
    "One sentence: who they serve, the problem in the customer's words, why them.",
    "",
    "## Offer",
    "What they sell, how it is priced, the problem it solves in customer language, and why them.",
    "",
    "## Audience",
    "B2B: ICP firmographics, buyer persona, trigger events, three named best-fit accounts.",
    "B2C: persona, desire, attention map, adjacent purchases.",
    "",
    "## Proof",
    "Results, numbers, named customers, testimonials, credentials, and the plain counts from their own diary or invoices, written as they said them. Note explicitly if thin, and write unknown rather than guessing.",
    "",
    "## Goal, next 90 days",
    "",
    "## Channels",
    "Active, dormant, and account status. Note IG account type for B2C, domain status and work email provider (Google, Microsoft 365, other) for B2B.",
    "",
    "## Numbers",
    "Labelled lines the 90 day plan projects from. Customers now, average monthly value, target in 90 days. Write unknown where they do not know yet.",
    "",
    "## Source material",
    "Five to ten accounts, competitors, newsletters or feeds their audience already reads. Topics only, not voice.",
    "",
    "## Voice",
    "Description of how they write or speak, plus three or four verbatim phrases.",
    "",
    "## Flags",
    "Anything the mentor team needs to know. Thin proof, no list, personal IG, fresh domain, unclear offer.",
    "```",
    "",
    "The Flags section is what the mentor team reads before the session. Be honest in it. A brain that hides a problem is worse than one that names it.",
    "",
    "## After writing",
    "",
    "1. Show the founder a short summary and confirm it is right.",
    "2. Tell them the Brain is now locked and every other engine reads from it. Locked means nothing rewrites it behind their back. It does not mean it can never change, and if they ask later they are not being difficult.",
    "3. Give them their gate submission line: track, business name, the thesis, and confirmation the file exists.",
    "4. Tell them what happens next, based on track:",
    "   - **B2B**: if the domain is fresh, set up SPF, DKIM and DMARC today and start sending ten to twenty real messages a day. Correct setup beats long warmup at 25-message volume, but it needs the weeks between now and Atlanta, not the last one.",
    "   - **B2C**: convert Instagram to Business or Creator today, and link it to a Facebook Page.",
    "",
    "Both of those are time-critical and founders will forget. Say them last so they are the thing remembered.",
    "",
  ].join('\n'),
  "founder-brain#unforked": [
    "# Founder Brain",
    "",
    "The Founder Brain is the input to every other engine. Nothing else runs without it.",
    "",
    "Output is a single file at `./growth-engine/founder-brain.md` in the founder's working folder.",
    "",
    "**Where the work lives.** Every file this makes for the founder sits in their `growth-engine/` folder, held for them, and they can see and download any of it from Files at any time. There is no folder to remember and nothing to keep in one place. Say this once, near the end, because founders arrive expecting to have to manage it.",
    "",
    "## Before starting",
    "",
    "Check whether `./growth-engine/founder-brain.md` already exists.",
    "",
    "- If it exists and the founder asked to build a new one, show them the current summary and ask whether to update it or start again.",
    "- If it exists and they asked to update, go straight to the section they want to change.",
    "- If it does not exist, run the full intake below.",
    "",
    "Create the `./growth-engine/` folder if it is not there.",
    "",
    "### If they ask to change the track",
    "",
    "\"change my track\" is a trigger on this skill, so a founder asking has reached the right place. It is allowed. Do not tell them it cannot be done, and do not send them to a mentor. There is no escalation path and inventing one leaves them stuck.",
    "",
    "It is the one change that costs a founder work, so it takes one honest exchange first. That is not the same as refusing.",
    "",
    "**Say what it costs, using their own file names.** Everything built off the track was written for the other side. Their Brain stays, their voice profile stays, and the rest is rebuilt.",
    "",
    "**Ask what changed.** Not to talk them out of it. \"I picked wrong in session 1\" is answered differently from \"I want to serve schools as well as parents\". The second one usually wants `hybrid: true` and the same track, and that distinction is worth thirty seconds of asking.",
    "",
    "**If they confirm, do it.** Rewrite the Track line in the file that is already there. Then reopen only the parts that fork on it, which are the audience capture and the channel question. Both are asked differently on each side, and the intake below already knows which. Everything else in the file is still true, so do not re-ask it and do not re-run the full intake.",
    "",
    "**Then say what to expect.** Their old track's files stay where they are and stop appearing in their list, because the list only shows the track they are on. The new track's gates start empty. Name which files they now need and which session covers each.",
    "",
    "If they are hesitating, leave it where it is. They can come back to it, and a track changed twice costs more than a track changed once.",
    "",
    "## Intake",
    "",
    "Ask these in small groups, not all at once. Three or four questions per turn. Reflect back what you heard before moving on. This should feel like a conversation with a sharp consultant, not a form.",
    "",
    "**Say where they are, every single turn.** Open each group by naming the stage",
    "and the count, like `Part 2 of 6: the track fork`. The six are the business, the",
    "track fork, the audience, the offer and proof, the channels, then the voice.",
    "When you finish the last one, say you are writing the file.",
    "",
    "This is not decoration. A founder who cannot see the end of a conversation does",
    "not know whether to give you a quick answer or a careful one, and the ones who",
    "guess wrong give you thin answers early and then run out of patience at the",
    "voice, which is the part everything else is built on. Knowing they are two",
    "thirds of the way through costs you one line and changes what they give you.",
    "",
    "### Group 1: the business",
    "",
    "1. What is the business called, and what does it sell?",
    "2. Who pays you? Be specific about the actual buyer.",
    "3. What stage are you at? Pre-revenue, first customers, under 10k a month, 10 to 50k, above 50k.",
    "4. What do you charge, and how? One-off, subscription, retainer, per unit.",
    "",
    "### Group 2: the track fork",
    "",
    "This is the most important question in the intake. Everything downstream branches from it.",
    "",
    "Ask: **does your revenue come mostly from selling to other businesses, or to individual consumers?**",
    "",
    "- Mostly businesses, so B2B",
    "- Mostly consumers, so B2C",
    "- Genuinely both",
    "",
    "If they say both, do not create a third track. Ask which motion produces more revenue today, or which one they most want to grow over the next 90 days. Record that as `track`, and record `hybrid: true` alongside it. The hybrid flag adjusts tone and examples later. It does not create a separate path.",
    "",
    "Explain briefly why you are asking: the outreach engine works completely differently on each track, and getting this wrong means building the wrong machine.",
    "",
    "**If track is B2C**, ask one more question: do they sell a service people book, or products people buy from a shop? Record the answer as `Model`, either `service` or `ecommerce`. It decides which operations snapshot they get and how their content is shaped. Never ask this of a B2B founder.",
    "",
    "### Group 3: audience",
    "",
    "**If track is B2B**, capture the ICP:",
    "- What kind of company? Industry, size, revenue band, geography.",
    "- Who is the individual you actually sell to? Job title, seniority, department.",
    "- What triggers them to start looking for something like yours?",
    "- Which companies are your best-fit customers today? Name three.",
    "",
    "**If track is B2C**, capture the persona:",
    "- Who is this person? Age range, life stage, situation.",
    "- What do they want that they cannot get right now?",
    "- Where do they already spend attention online? Be specific about platforms and accounts.",
    "- What do they already buy that sits next to your product?",
    "",
    "Do not ask B2B questions of a B2C founder or the reverse. It wastes their time and signals the tool does not understand them.",
    "",
    "### Group 4: offer and proof",
    "",
    "1. What problem do you solve, in one sentence, in their words rather than yours?",
    "2. Why you rather than the obvious alternative?",
    "3. What proof do you have? Results, numbers, named customers, case studies, testimonials, credentials.",
    "4. What do you want more of in the next 90 days? Leads, sales, followers, retention.",
    "",
    "**Ask question 3 in their world, not in business language.** Most founders here run small local businesses, so the countable things are dogs, weddings, kitchens, boilers, meals, sessions, callouts and repeat bookings, not customers and firms. Ask how many they have done, how long they have been doing it, how many come back, and which one went best. Write the numbers down exactly as they said them, and write unknown where they do not know.",
    "",
    "That last part is the important one. A number recorded here is a number every other engine is allowed to use. A gap recorded here is a gap nothing downstream will quietly fill in for them.",
    "",
    "Proof matters more than founders expect. It is the raw material for every post and every message. If they have none, say so plainly and note it, because the content engine will lean on story and point of view instead.",
    "",
    "### The thesis",
    "",
    "From their Group 4 answers, compose one sentence: who they serve, the problem in the customer's own words, and why them rather than the obvious alternative. Read it back and adjust until they would say it out loud to a stranger. This is the thesis. It goes in the Brain, it is pressure-tested in Session 1, and it is part of their Gate 1 submission.",
    "",
    "### Group 5: channels",
    "",
    "- Where do you currently publish, if anywhere?",
    "- Which channels do you have accounts on but do not use?",
    "- **If track is B2C**: is your Instagram a personal account, or Business or Creator? If personal, tell them to convert it now, because publishing and inbound capture will not work without it, and it takes two minutes.",
    "- **If track is B2B**: which provider is their work email on, Google (Gmail or Google Workspace), Microsoft 365, or something else? This decides how they send their 25 messages later, so record it plainly. It is not a technical question to them: \"what do you open your work email in\" gets the answer.",
    "- **If track is B2B**: do you have a business domain with real email sending history, or will you need a fresh domain? A fresh domain needs SPF, DKIM and DMARC configured now, plus ten to twenty real messages a day between now and the event. At 25 messages, correct setup matters more than months of warmup, but it cannot be crammed into the last week, so flag it as a start-today item.",
    "",
    "## Voice capture",
    "",
    "Three paths. Pick based on what they have. Nobody gets stuck here.",
    "",
    "**Important distinction before you start.** The voice must be theirs. Curated content from other people is useful for working out what to write *about*, never for how it sounds. If you train the voice on a competitor, the founder ends up publishing something that reads like an imitation, and their audience can tell. Topics can be borrowed. Voice cannot.",
    "",
    "### Path A: they have writing",
    "",
    "Ask for 10 to 20 samples of anything they have written in their own voice. Posts, emails, newsletters, even long messages. Pasted in, or a file path.",
    "",
    "Read them and extract:",
    "- Sentence length and rhythm",
    "- Vocabulary level and any recurring words or phrases",
    "- How they open and how they close",
    "- Whether they use humour, and what kind",
    "- First person singular or plural",
    "- How direct they are, and how much they hedge",
    "- Formatting habits: lists, line breaks, questions, emoji",
    "",
    "### Path B: they have some writing, but not much",
    "",
    "Five or six real samples is enough to work from. Read them the same way as Path A, then fill the gaps with two or three interview questions from Path C. Say plainly that a smaller sample is fine and that you will check the result with them before anything gets built on it.",
    "",
    "### Path C: they have nothing written",
    "",
    "Many early-stage and B2C founders have no body of writing. This is normal. Do not make it awkward.",
    "",
    "Run a short interview instead, and capture how they *speak*:",
    "- Tell me about the last customer you really enjoyed working with.",
    "- What do people get wrong about your industry?",
    "- What would you say to someone about to make the mistake your product prevents?",
    "- What is the thing you find yourself explaining over and over?",
    "",
    "Their answers to these are the voice sample. Pay attention to how they actually phrase things, not what they say.",
    "",
    "### Source material, all three paths",
    "",
    "Separately from voice, ask what they already read and who they follow in their space. Competitors, industry accounts, newsletters, creators. This is not for voice. It is so the content engine knows what conversations their audience is already having, and what the founder wants to agree with or argue against.",
    "",
    "Record five to ten of these in the Brain under Source material. A founder with a strong point of view and no writing history will produce better content from this than a founder with fifty posts and nothing to react to.",
    "",
    "### Voice profile",
    "",
    "Either path produces the same output: a description specific enough that another writer could imitate it. Include three or four verbatim phrases they actually use.",
    "",
    "Then show the founder a two-sentence sample written in their captured voice and ask: does this sound like you? Adjust until they say yes. Do not skip this check.",
    "",
    "## Writing the file",
    "",
    "Write `./growth-engine/founder-brain.md` in this shape:",
    "",
    "```markdown",
    "# Founder Brain",
    "",
    "- **Founder:**",
    "- **Business:**",
    "- **Track:** b2b | b2c",
    "- **Model:** service | ecommerce, B2C only, leave out for B2B",
    "- **Hybrid:** true | false",
    "- **Stage:**",
    "- **Locked:** YYYY-MM-DD",
    "",
    "## Thesis",
    "One sentence: who they serve, the problem in the customer's words, why them.",
    "",
    "## Offer",
    "What they sell, how it is priced, the problem it solves in customer language, and why them.",
    "",
    "## Audience",
    "B2B: ICP firmographics, buyer persona, trigger events, three named best-fit accounts.",
    "B2C: persona, desire, attention map, adjacent purchases.",
    "",
    "## Proof",
    "Results, numbers, named customers, testimonials, credentials, and the plain counts from their own diary or invoices, written as they said them. Note explicitly if thin, and write unknown rather than guessing.",
    "",
    "## Goal, next 90 days",
    "",
    "## Channels",
    "Active, dormant, and account status. Note IG account type for B2C, domain status and work email provider (Google, Microsoft 365, other) for B2B.",
    "",
    "## Numbers",
    "Labelled lines the 90 day plan projects from. Customers now, average monthly value, target in 90 days. Write unknown where they do not know yet.",
    "",
    "## Source material",
    "Five to ten accounts, competitors, newsletters or feeds their audience already reads. Topics only, not voice.",
    "",
    "## Voice",
    "Description of how they write or speak, plus three or four verbatim phrases.",
    "",
    "## Flags",
    "Anything the mentor team needs to know. Thin proof, no list, personal IG, fresh domain, unclear offer.",
    "```",
    "",
    "The Flags section is what the mentor team reads before the session. Be honest in it. A brain that hides a problem is worse than one that names it.",
    "",
    "## After writing",
    "",
    "1. Show the founder a short summary and confirm it is right.",
    "2. Tell them the Brain is now locked and every other engine reads from it. Locked means nothing rewrites it behind their back. It does not mean it can never change, and if they ask later they are not being difficult.",
    "3. Give them their gate submission line: track, business name, the thesis, and confirmation the file exists.",
    "4. Tell them what happens next, based on track:",
    "   - **B2B**: if the domain is fresh, set up SPF, DKIM and DMARC today and start sending ten to twenty real messages a day. Correct setup beats long warmup at 25-message volume, but it needs the weeks between now and Atlanta, not the last one.",
    "   - **B2C**: convert Instagram to Business or Creator today, and link it to a Facebook Page.",
    "",
    "Both of those are time-critical and founders will forget. Say them last so they are the thing remembered.",
    "",
  ].join('\n'),
  "ghl-workflows": [
    "# Operations Engine",
    "",
    "Delivers the page promise: one workflow running on the founder's live business before they leave Atlanta.",
    "",
    "The workflow itself is a pre-built GoHighLevel snapshot, loaded in one click at the clinic. This skill does the two things that actually need thinking: choosing the right one, and writing the words inside it.",
    "",
    "**Founders do not build workflows.** If a founder starts describing a bespoke automation, bring them back to the library. Bespoke is what fails at 130.",
    "",
    "## Prerequisites",
    "",
    "Read `./growth-engine/founder-brain.md`.",
    "",
    "If it genuinely does not exist, stop. Tell the founder to open Founder Brain, or to say \"build my founder brain\", and do not proceed. Do not ask them to describe their business again from scratch, and do not guess at their offer, audience or voice. Everything this skill produces is only as good as the Brain behind it.",
    "",
    "Use it for track, stage, offer and goal.",
    "",
    "## Step 1: bottleneck diagnostic",
    "",
    "Find the one repetitive task that costs the most time or leaks the most revenue. Ask:",
    "",
    "1. What do you do every week that you resent doing?",
    "2. Where do people go quiet on you, and what happens next?",
    "3. What do you forget to do, and what does it cost when you forget?",
    "4. If one repetitive job disappeared on Monday, which one?",
    "",
    "Then name the bottleneck in one sentence, in their words. Confirm it with them before moving on. Getting this wrong means automating the wrong thing.",
    "",
    "## Step 2: pick the snapshot",
    "",
    "One only. Two half-finished workflows are worse than one running.",
    "",
    "### B2B library",
    "",
    "| Snapshot | Runs on | Use when |",
    "|---|---|---|",
    "| Lead follow-up | Email | Inbound leads are not chased consistently |",
    "| Discovery booking | Email | Booking a call takes too many messages |",
    "| Proposal chase | Email | Proposals go quiet and nobody follows up |",
    "",
    "### B2C library",
    "",
    "| Snapshot | Runs on | Use when |",
    "|---|---|---|",
    "| Comment-to-DM capture | Instagram | Content gets engagement but no conversation |",
    "| DM qualify and book | Instagram | DMs arrive but conversion is manual and slow |",
    "| Review request | Email and SMS | Reviews are never asked for |",
    "",
    "The library is deliberately small. If the founder's bottleneck falls outside these six, for example onboarding, reactivation, abandoned checkout or win-back, pick the nearest snapshot and adapt the message copy to it, and note the gap in the output file so a mentor can help individually. Do not invent a snapshot that does not exist and do not attempt a bespoke build.",
    "",
    "**Name the platform from the table, never from memory.** A B2C snapshot runs on Instagram. Saying one runs on LinkedIn puts the other track's platform in front of a founder who is not on it, and it sends them to the wrong place on the day.",
    "",
    "Recommend one and explain why against their stated bottleneck. Let them override.",
    "",
    "## Step 3: write the copy",
    "",
    "The snapshot is the plumbing. The copy is the founder's.",
    "",
    "For the chosen snapshot, write every message it sends: emails with subject lines, SMS, DM replies, internal notifications. Written in the captured voice, matched to track.",
    "",
    "Also specify: the trigger, the wait intervals between steps, the exit condition, and which tags get applied.",
    "",
    "Keep waits realistic. Chasing someone four times in two days annoys them.",
    "",
    "**On the two DM snapshots, check the trigger before you write a word.** Both start with something the other person did: a comment on a post, or a message they sent in. Write the copy as the answer to that. If you find yourself writing to somebody who has done neither, the trigger is wrong, and no amount of rewriting the copy fixes it.",
    "",
    "**No message claims a result the Brain does not record.** A review request that says join our 200 happy customers is an invented number, sent to a real customer who can count. If the Brain has no number, ask for the review on the work the founder actually did for that person, and name the work.",
    "",
    "## Step 4: n8n escape hatch",
    "",
    "Only if the data lives outside GoHighLevel. Stripe to a spreadsheet, Shopify to Airtable, a legacy system, multi-API orchestration.",
    "",
    "Roughly one founder in six needs this. If the founder does not clearly need it, do not raise it. If they do, note the requirement in the output file and flag it for one-to-one support rather than trying to solve it here.",
    "",
    "## Step 5: export",
    "",
    "Write `./growth-engine/ops-workflow.md` containing the named bottleneck, the chosen snapshot, all message copy, the trigger, the timings, the exit condition, and the tags.",
    "",
    "The founder takes this to the setup clinic on 23 September, loads the snapshot, and pastes the copy in.",
    "",
    "## Gate",
    "",
    "Bottleneck named in one sentence, snapshot chosen, all copy written.",
    "",
  ].join('\n'),
  "growth-plan": [
    "# 90-Day Growth Plan",
    "",
    "The Sunday deliverable. Sequences everything built over the weekend into one plan the founder can execute from Monday.",
    "",
    "## Prerequisites",
    "",
    "Read all of these that exist:",
    "- `./growth-engine/founder-brain.md`",
    "- `./growth-engine/content-30.md`",
    "- `./growth-engine/outreach-sequence.md` (B2B) or `./growth-engine/dm-openers.md` and `inbound-scripts.md` (B2C)",
    "- `./growth-engine/ops-workflow.md`",
    "",
    "If `founder-brain.md` itself is missing, stop and tell the founder to open Founder Brain, or to say \"build my founder brain\". There is no plan to build without it.",
    "",
    "If the Brain exists but engine files are missing, build the plan from what exists and note the gaps honestly. Do not pretend an engine is running when it is not.",
    "",
    "Read the `track` field. A B2B plan sequences the sequence, the list and the sending. A B2C plan sequences the DMs, the hooks and the inbound machine. Never put the other track's work in a founder's plan.",
    "",
    "## Structure",
    "",
    "**The one number.** One primary metric for 90 days, derived from the Brain's stated goal. Not a vanity metric. Something that moves revenue.",
    "",
    "**Days 1 to 30.** Get all three engines running consistently. Weekly actions, specific and small enough to actually happen.",
    "",
    "**Days 31 to 60.** Volume and iteration. What gets tested, what gets measured. On the B2C track, volume never means more first messages a day. It means more posts, more hooks, and more of the inbound side switched on.",
    "",
    "**Days 61 to 90.** Double down or cut, based on the data.",
    "",
    "**Monday morning.** The first three actions, in order, with time estimates. This is the most important section. Most plans die because nobody knows what to do first.",
    "",
    "**Kill criteria.** What result at day 30 means stop. Founders never write these and it is why they persist with things that are not working. Push for a real number.",
    "",
    "**Realistic numbers.** Base projections on their actual list size, audience size and conversion assumptions. Do not use the marketing numbers from the landing page. If the maths says a modest outcome, say so.",
    "",
    "Every number in this plan is either one the founder gave you, or an assumption. Label the assumptions in the text, with the word assume, and show the arithmetic in one line so they can change an input and see what moves. A projection that does not say it is a projection becomes a fact the moment it gets pasted somewhere else.",
    "",
    "## Output",
    "",
    "Write `./growth-engine/90-day-plan.md`.",
    "",
    "Keep it to two pages. A plan nobody reads is not a plan.",
    "",
    "## Pressure test",
    "",
    "The founder presents this in the Sunday pressure-test session. Prepare them for three questions: is the number realistic, what happens if it does not work, and what is the first thing you do Monday.",
    "",
  ].join('\n'),
  "help": [
    "# Help",
    "",
    "The founder's first stop when something is not working or they are not sure what to do next.",
    "",
    "Be plain and unhurried. Many founders on this programme are not technical and will already feel behind.",
    "",
    "## Two ways in",
    "",
    "**They asked for help.** Work out what they are trying to do, answer it, and point them at the one thing to do next.",
    "",
    "**Something is broken.** The founder has a problem, so start by asking what is happening in their own words, then run the checks most likely to be relevant rather than all of them in order.",
    "",
    "If two attempts do not resolve it, stop and tell them to post in the Slack channel. Do not leave them grinding.",
    "",
    "## Check progress",
    "",
    "Hand off to the status skill rather than duplicating it here.",
    "",
    "## Time-critical items",
    "",
    "Read `./growth-engine/founder-brain.md` if it exists and check the Flags section.",
    "",
    "- **B2B**: is the sending domain sorted, with SPF, DKIM and DMARC configured? If the Brain flags a fresh domain and nothing has happened, raise it now.",
    "- **B2C**: is Instagram converted to Business or Creator and linked to a Facebook Page? Nothing publishes or captures inbound without it.",
    "",
    "Raise these even if the founder asked about something else. They are the two items that quietly break the weekend.",
    "",
    "## Common problems",
    "",
    "**\"It gave me LinkedIn posts and I sell to consumers.\"** The track field in their Brain is wrong. Tell them to say \"change my track\", which reopens the Founder Brain on that one line, then regenerate the content.",
    "",
    "**\"My files disappeared.\"** Almost never true. Open Files. Every file they have made is listed there, with every earlier version of it.",
    "",
    "**\"It will not let me automate Instagram DMs.\"** Correct behaviour, not a bug. Instagram only opens a reply window once somebody has written to you first, and the accounts that get round that are the ones that get restricted. Say that plainly, then take them to the inbound side and build it with them.",
    "",
    "**\"I cannot get any of this working.\"** Do not keep troubleshooting past two failed attempts. Tell them to post in the Slack channel and that someone will sort it individually. A founder stuck alone for an hour is worse than a founder who asked for help after ten minutes.",
    "",
    "## What this skill does not do",
    "",
    "It does not change any founder content. Diagnosis and repair of setup only.",
    "",
  ].join('\n'),
  "outreach-b2b": [
    "# Outreach Engine, B2B",
    "",
    "Produces the sequence and the 25 personalised messages sent live on Saturday.",
    "",
    "## Prerequisites",
    "",
    "Read `./growth-engine/founder-brain.md`.",
    "",
    "If it genuinely does not exist, stop. Tell the founder to open Founder Brain, or to say \"build my founder brain\", and do not proceed. Do not ask them to describe their business again from scratch, and do not guess at their offer, audience or voice. Everything this skill produces is only as good as the Brain behind it.",
    "",
    "If `track` is not `b2b`, stop and route the founder to the audience-b2c skill instead. Do not run a B2B sequence for a B2C founder.",
    "",
    "## Step 0: what is going to send this",
    "",
    "Decide this before writing a word, because it changes the merge variables and the export.",
    "",
    "Ask one question: **is their work email on Google (Gmail or Google Workspace), or on Microsoft 365, or something else?**",
    "",
    "**If Google.** They build the list and send from Apollo. The free plan connects in full, so session 3 costs them nothing. Apollo does not run its own mail servers: every message leaves through their own connected mailbox by a two-minute sign-in, so their domain carries the reputation either way. Sequences handle the follow-up touches, and stop-on-reply is on by default, which is the whole reason to use a sequencer at this volume.",
    "",
    "**If Microsoft 365 or anything else.** They send by hand from their own mailbox and schedule the follow-ups with their mail app's own scheduled send. This is a real route, not a consolation. At 25 messages it meets the promise completely, costs nothing, needs no new account, and replies land where they already read email.",
    "",
    "Record the answer in the output file. Nobody chooses twice.",
    "",
    "**On the cost, and get this the right way round.** The free plan connects to the app in full, so nothing in session 3 needs paying for. The 65 USD/month plan is what actually sends, and it is bought at the setup clinic on 23 September, alongside GoHighLevel and for the same reason: a plan bought in September is running on the Saturday, and one bought in August has been paid for three weeks of not sending yet.",
    "",
    "Say it that way round. Telling a founder they need the plan to connect it is not true, they will find that out, and every other number in this programme is worth less to them afterwards.",
    "",
    "They are already carrying Claude, a domain and GoHighLevel at 97 USD. A founder who says the total is too much is doing arithmetic rather than hesitating, and arguing is how this skill loses them. That founder takes the manual route, which is real and meets the promise at 25 messages.",
    "",
    "**On the manual route, schedule two touches at a time, never all four.** If someone replies, there are only two things to cancel, and cancelling is the job people forget.",
    "",
    "## Step 1: list criteria",
    "",
    "Convert the ICP into filters a founder can type into Apollo.",
    "",
    "Output the criteria as a plain list they can copy: industry, headcount band, revenue band, geography, job titles, seniority, and any technology or keyword filters that indicate the trigger event.",
    "",
    "Give three variants: tight, medium, broad. Tight is the best-fit list and may be small. Broad is the fallback if tight returns under 100 results.",
    "",
    "**Build to 35, then cut to 25.** Some rows will be wrong: the person left, the address bounces, the company is not a fit on a second look. Topping up a list under time pressure on the Saturday is how founders end up messaging people they have not read.",
    "",
    "Tell them to build the list as homework and to verify emails before sending. An unverified list destroys domain reputation faster than bad copy.",
    "",
    "## Step 2: sequence",
    "",
    "Four to five touches over two to three weeks.",
    "",
    "- Touch 1: the opener. Specific to them, one clear reason for the message, one low-friction ask.",
    "- Touch 2: proof. A result or case relevant to their situation, taken from the Brain's Proof section and from nowhere else.",
    "- Touch 3: a different angle on the same problem.",
    "- Touch 4: a short, direct close.",
    "- Touch 5, optional: the break-up.",
    "",
    "Rules that are not negotiable:",
    "- Under 120 words per touch. Shorter converts.",
    "- One ask per message.",
    "- A subject line on touch 1, and a decision for each later touch on whether it replies in the same thread or starts a new one. Same thread is the default.",
    "- A wait interval stated between every touch. Three to four working days is the normal spacing across two to three weeks.",
    "- **A plain opt-out line in the body of every touch.** One sentence, their own words, for example \"if this is not for you, say so and I will leave you alone\". Do not rely on a tool's unsubscribe link, because the free plan may not have one, and at this volume a human sentence reads better anyway. This is not optional: it is what the law expects and what a real person deserves.",
    "- Written in the founder's captured voice, not in generic sales English.",
    "- No fake familiarity, no invented compliments, no \"I noticed you...\" unless it is genuinely specific.",
    "",
    "**Merge variables.** Only if they are sending through Apollo. Apollo uses `{{contact.first_name}}` and `{{account.name}}`. The older `{{first_name}}` and `{{company}}` still work.",
    "",
    "The personalised opening line is not one of those. It is a custom field on the contact, holding a different sentence for every person, referenced in the template by its own name. So the sequence has one body and each recipient reads a line written for them. Whoever builds the sequence sets that field per contact before anybody is enrolled.",
    "",
    "**On the manual route there are no merge variables at all.** Write all 25 messages out in full, finished, with the name and detail already in the text. There is nothing to substitute and nothing to go wrong.",
    "",
    "**Stop on reply.** In Apollo this is on by default, as is pausing on an out of office. Confirm it is on rather than assuming. On the manual route this is the founder's job, and it is the single thing most likely to be forgotten three weeks after the event.",
    "",
    "**Never write a claim the Brain does not support, and never write a number the founder did not give you.**",
    "",
    "If the Proof section is thin, touch 2 is still touch 2. Write it from one of these instead, in this order:",
    "",
    "- The one named case they do have, in the detail they gave you.",
    "- What they have seen across the jobs they have done. The fault that turns up again and again, the thing every owner says in the first meeting.",
    "- The step they take that the cheaper option skips. That is method, and it needs no number at all.",
    "",
    "A specific observation about the reader's own world reads as true. A number nobody gave you can be checked, and in a trade this size somebody will check it.",
    "",
    "## Step 3: first lines",
    "",
    "**Where the list comes from.** With the Apollo connector on their Claude account, they can ask for the search to be run and the addresses filled in, and the list arrives without anybody typing it. Without it, they run the search in Apollo themselves and paste the leads in. Either way what happens next is the same.",
    "",
    "For each person, generate one opening line specific to that company or that person.",
    "",
    "Ask for whatever they have: company name, website copy, a recent post, a job ad, a news item. Generate from the actual detail. If there is nothing specific, say so and write a line based on the segment rather than fabricating a detail. **A generic honest line beats an invented specific one.**",
    "",
    "Work in batches of 5 to 10 so the founder can check quality as it goes.",
    "",
    "## Step 4: deliverability brief",
    "",
    "Cover this even though it is not copy, because it decides whether any of it works.",
    "",
    "- 25 messages is low volume. At this scale, authentication matters more than warmup duration.",
    "- SPF, DKIM and DMARC must all be configured. Without them, mail gets filtered no matter how old the domain is.",
    "- An existing domain with real sending history is still better than a fresh one. Use it if they have it.",
    "- On a fresh domain, sending ten to twenty normal messages a day in the weeks beforehand is sufficient at this volume.",
    "- Verify every email before sending. An unverified list does more damage than a cold domain.",
    "- Never promise replies. Replies depend on list quality, timing and offer, none of which are guaranteed.",
    "- Turn open and click tracking off. Tracking pixels and rewritten links are a spam signal, and at 25 messages the data is worth nothing.",
    "- **Say this plainly, once.** Best practice for high-volume cold email is to send from a separate outreach subdomain, never the main company domain. This programme sends from the main domain on purpose, because 25 authenticated, genuinely personalised messages with an opt-out line carry low risk and setting up a second domain properly is more work than the runway allows. The risk is low. It is not zero. The founder should know that rather than find out.",
    "",
    "## Step 5: export",
    "",
    "Write `./growth-engine/outreach-sequence.md` containing: the chosen route from Step 0, the full sequence with subject lines, wait intervals and the opt-out line, and the merge variables if any.",
    "",
    "Write `./growth-engine/outreach-firstlines.csv` with columns `email`, `first_name`, `company`, `first_line`.",
    "",
    "`first_line` holds the generated opening line. Name it `first_line` rather than anything generic, so the CSV column, the Apollo custom field and the variable in the sequence all read the same. A mismatch here fails silently and takes the most valuable output of this skill with it.",
    "",
    "**Sending it.** With the connector, the sequence is built in their Apollo account with the copy already in it, paused, and starting it is a button they press in Apollo having read the messages. Nothing sends before that and nothing here can make it.",
    "",
    "**On the manual route, the CSV is a checklist, not an import.** It is the founder's running sheet for Saturday: who, what the opening line is, and a column to tick when sent.",
    "",
    "This is a cold list, so it never goes into GoHighLevel's email tool. GoHighLevel is the CRM and the publisher for this programme. It is not the cold sender.",
    "",
    "## Gate",
    "",
    "Route chosen and recorded, sequence approved with opt-out line and wait intervals, list criteria defined, list built to 35 and cut to 25, first lines generated for all 25.",
    "",
  ].join('\n'),
  "playbook-export": [
    "# Playbook Export",
    "",
    "Produces the four to six page personalised insert that prints with the generic playbook body.",
    "",
    "## Prerequisites",
    "",
    "Read every file in `./growth-engine/`.",
    "",
    "If `founder-brain.md` does not exist, stop and tell the founder to open Founder Brain, or to say \"build my founder brain\". There is nothing to compile.",
    "",
    "This is a compilation task, not a generation task. Do not invent content that is not already in the founder's own files. If a section has no source file, leave it out and say so, rather than writing filler.",
    "",
    "## Contents",
    "",
    "1. **Cover.** Founder name, business, track.",
    "2. **Your Brain.** Offer, audience, proof, voice, in one page.",
    "3. **Your content.** Pillars and the 30 pieces, titles and openers only, not full text.",
    "4. **Your engine 2.** B2B: the sequence. B2C: the hook bank and inbound scripts.",
    "5. **Your ops.** Bottleneck, snapshot, and message copy.",
    "6. **Your 90 days.** The plan, the number, Monday's three actions, kill criteria.",
    "",
    "## Output",
    "",
    "Write `./growth-engine/playbook-insert.md`, formatted for print. Clean headings, no clutter, generous white space, page breaks between sections.",
    "",
    "## Delivery",
    "",
    "The generic playbook body prints in two variants, B2B and B2C, and goes to the printer in early September. **The personalised insert is delivered as a PDF, not printed.** Founders receive it digitally before Atlanta and can print it themselves if they want a hard copy.",
    "",
    "Keep the insert to six pages maximum. Format it so it converts cleanly to PDF: no wide tables, no colour dependence, page breaks between sections.",
    "",
  ].join('\n'),
  "status": [
    "# Status",
    "",
    "Tells the founder exactly where they stand and what is outstanding.",
    "",
    "## Report",
    "",
    "Read whatever exists and report against this checklist. Show track first, because the checklist branches.",
    "",
    "| File | What it has to contain | Session |",
    "|---|---|---|",
    "| founder-brain.md | Brain locked, thesis written | 1 |",
    "| content-30.md and content-30.csv | 30 pieces generated and edited | 2 |",
    "| rss-feeds.md | Source list for the monthly refill | 2 |",
    "| outreach-sequence.md, outreach-firstlines.csv | B2B: sequence approved, list criteria defined, list built, first lines for the first 25 | 3 |",
    "| dm-openers.md, hook-bank.md, inbound-scripts.md | B2C: 25 openers, hook bank with offer tests, inbound scripts | 3 |",
    "| ops-workflow.md | Bottleneck named, snapshot chosen, copy written | 3 |",
    "| 90-day-plan.md | The number, Monday's three actions, kill criteria | Weekend |",
    "| playbook-insert.md | Brain, content, engine 2, ops and 90 day plan, gathered into one document | 3 |",
    "",
    "**playbook-insert.md is not made in this app.** It is generated in Claude at session 3, out of the files above. A founder cannot build it here and there is no engine to send them to.",
    "",
    "So when it is missing, that is expected. Say it is made later, in Claude, and move on. Do not offer to write it, do not ask what it is for, and do not count it against them.",
    "",
    "Every row says what the file has to contain, not when it is due. That is what",
    "lets you tell a founder whether a file counts, and it is the second column for",
    "that reason.",
    "",
    "Also check the Brain's Flags section and surface anything unresolved, particularly domain warmup status for B2B and Instagram account type for B2C.",
    "",
    "## A file you cannot account for",
    "",
    "The checklist above is the whole list. If the folder holds something that is not",
    "on it, say what you can see and move on.",
    "",
    "Never ask the founder to explain what one of their own files is for, and never",
    "offer them a list of things it might have been. They opened this to be told",
    "where they stand. A file this skill cannot name is this skill's gap, not their",
    "homework, and guessing at it in front of them turns a status check into a",
    "question they cannot answer.",
    "",
    "## Be direct",
    "",
    "Say what is missing and what to run next. One clear next action, not a list of six.",
    "",
    "If they are behind, say so plainly and tell them which single thing to do first. Do not soften it. The gates exist so nobody arrives in Atlanta unable to build.",
    "",
  ].join('\n'),
};

/**
 * sha256 of each body.
 *
 * Here so a deployment can print what it is actually running and a cost report
 * can group by it. Two containers serving one route must print the same hash,
 * and if they do not, the prompt cache is not being shared and the bill says so.
 */
export const SKILL_BODY_SHA256: Readonly<Record<string, string>> = {
  "audience-b2c": "4e6f8857b4da0e3109ce374e87512d43dbc9a2e1481e9883ad54acdeff722581",
  "content-engine": "fba5ea53ebd099531496275d309a127e584762f802005eeafd19faa5d755cc09",
  "content-engine#unforked": "738f460b5372f0774f9eeb72cd9fa3196c1a635720be59dbd8e34875752a5371",
  "founder-brain": "1a82f3afd06845d6c9501d59b38095172bb8d597569bfecf938064f17c11cb05",
  "founder-brain#unforked": "47b9170691252bb9a4a816cc5e6534cfc55f1d71d27379cd1dd4b120d05be488",
  "ghl-workflows": "160df84affa4ad772d66346a929f5fc2a7c7e2d89616507c47236561e57d4d65",
  "growth-plan": "cbc017e7f69ccb622b24e6ea34e465460ba7eff85ebe4ad2ccc6c794cd937df8",
  "help": "cd95a44d4160de89fda9c910506a5e8c8b94e3fd896e8c7c038cc5d1081d838f",
  "outreach-b2b": "93672f9acd7441dd4de22740c777f6c7cc5ea9f1c7900ef51511a0aed3d15712",
  "playbook-export": "4f58f80ebaf1faaea1f72177fc9a89115aa63b4551c365fed35140edb759fd07",
  "status": "c306a4c4551b7626a930e26685b82e4cb7d44d9bb34bf3386c323d4550b00d35",
};

/** The keys, in the order they are declared above. */
export const SKILL_KEYS: readonly string[] = Object.keys(SKILL_BODIES);
